name: "mt_analytics"
version: "1.0.0"
config-version: 2

profile: "mt_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  mt_analytics:
    # Staging models - source data
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]

    # Intermediate models - business logic
    intermediate:
      +materialized: view
      +schema: staging
      +tags: ["intermediate"]

    # Marts - analytics-ready tables
    marts:
      +materialized: table
      +schema: analytics
      +tags: ["marts"]

      # Metrics models
      metrics:
        +materialized: view
        +schema: analytics
        +tags: ["metrics"]

# Variables for multi-tenant configuration
vars:
  # Default tenant for testing
  current_tenant_id: "11111111-1111-1111-1111-111111111111"

  # Event types to process
  event_types:
    - "page_view"
    - "button_click"
    - "form_submit"
    - "api_call"
    - "feature_usage"

  # Lookback window for incremental models
  lookback_days: 3

# Seeds configuration
seeds:
  mt_analytics:
    +schema: raw
