mt_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'analytics_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'analytics_pass') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'analytics_db') }}"
      schema: staging
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10

    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'analytics_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'analytics_pass') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'analytics_db') }}"
      schema: analytics
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
