version: 2

sources:
  - name: raw
    description: Raw layer with data ingested from Kafka
    schema: raw
    tables:
      - name: events
        description: Raw event data from all tenants
        columns:
          - name: event_id
            description: Primary key for events
            tests:
              - unique
              - not_null
          - name: tenant_id
            description: Foreign key to tenants table
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'tenants')
                  field: tenant_id
          - name: event_type
            description: Type of event
            tests:
              - not_null
              - accepted_values:
                  values:
                    [
                      "page_view",
                      "button_click",
                      "form_submit",
                      "api_call",
                      "feature_usage",
                    ]
          - name: event_timestamp
            description: When the event occurred
            tests:
              - not_null

      - name: tenants
        description: Master tenant table
        columns:
          - name: tenant_id
            description: Primary key for tenants
            tests:
              - unique
              - not_null
          - name: tenant_name
            description: Unique tenant name
            tests:
              - unique
              - not_null
          - name: status
            tests:
              - accepted_values:
                  values: ["active", "inactive", "suspended"]

models:
  - name: stg_events
    description: Cleaned and standardized event data
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: tenant_id
        tests:
          - not_null
      - name: is_invalid_timestamp
        description: Flag for data quality issues
        tests:
          - accepted_values:
              values: [true, false]

  - name: stg_tenants
    description: Cleaned tenant dimension
    columns:
      - name: tenant_id
        tests:
          - unique
          - not_null
      - name: tier_level
        description: Numeric tier ranking
        tests:
          - not_null

  - name: fct_usage_events
    description: Primary fact table for usage analytics
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: tenant_id
        tests:
          - not_null
    tests:
      - dbt_utils.expression_is_true:
          expression: "event_timestamp <= CURRENT_TIMESTAMP"
          config:
            severity: warn

  - name: dim_tenants
    description: Tenant dimension table
    columns:
      - name: tenant_id
        tests:
          - unique
          - not_null

  - name: tenant_usage_metrics
    description: Aggregated usage metrics per tenant
    columns:
      - name: tenant_id
        tests:
          - not_null
      - name: total_events
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
